version: '2'
services:
    src:
        build: ./src
        ports:
            - "5000:5000"
        environment:
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - FACEBOOK_APP_ID
            - FACEBOOK_APP_SECRET
    static:
        build: ./static
        ports:
            - "80:80"
